<?php

namespace App\Support\Patients;

use App\Models\Patient;
use InvalidArgumentException;

final class PatientClinicalHistoryNumber
{
    /**
     * Provisional business mapping confirmed for new patient records.
     *
     * RUC and SIN DOCUMENTOS are deliberately absent: neither has an approved,
     * stable HCE rule in the current functional definition.
     */
    private const DOCUMENT_CODES = [
        'DNI' => '01',
        'CARNET EXTRANJERIA' => '02',
        'PASAPORTE' => '03',
        'PTP' => '04',
        'TAM' => '05',
        'SALVOCONDUCTO' => '06',
    ];

    /**
     * @return list<string>
     */
    public static function supportedDocumentTypes(): array
    {
        return array_keys(self::DOCUMENT_CODES);
    }

    public function generate(string $documentType, string $documentNumber): ?string
    {
        $type = trim($documentType);
        $number = trim($documentNumber);

        if (!isset(self::DOCUMENT_CODES[$type])) {
            return null;
        }

        if ($number === '') {
            throw new InvalidArgumentException('El número de documento es obligatorio para asignar la HCE.');
        }

        $clinicalHistoryNumber = self::DOCUMENT_CODES[$type].'-'.$number;

        if (mb_strlen($clinicalHistoryNumber) > 255) {
            throw new InvalidArgumentException('El número de documento es demasiado largo para asignar la HCE.');
        }

        return $clinicalHistoryNumber;
    }

    /**
     * Assign an HCE only to a model that has never been persisted.
     *
     * Existing rows, including inherited rows with a null HCE, are never
     * backfilled or regenerated by ordinary reads or edits.
     */
    public function assignToNewPatient(Patient $patient): void
    {
        if ($patient->exists || filled($patient->historia_clinica)) {
            return;
        }

        $clinicalHistoryNumber = $this->generate(
            (string) $patient->tipo_identificacion,
            (string) $patient->numero_identidad
        );

        if ($clinicalHistoryNumber !== null) {
            $patient->historia_clinica = $clinicalHistoryNumber;
        }
    }
}
